# Generated by Django 5.0.1 on 2024-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cityweather",
            name="speed_unit",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cityweather",
            name="temp_unit",
            field=models.CharField(max_length=30),
        ),
    ]
