# Generated by Django 5.0.1 on 2024-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_alter_cityweather_speed_unit_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cityweather",
            options={
                "verbose_name": "Weather Data",
                "verbose_name_plural": "Weather Data",
            },
        ),
        migrations.AddField(
            model_name="cityweather",
            name="current",
            field=models.BooleanField(default=False),
        ),
    ]
