# Generated by Django 5.0.1 on 2024-01-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_alter_cityweather_options_cityweather_current"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentWeather",
            fields=[
                ("city_id", models.IntegerField(primary_key=True, serialize=False)),
                ("weather", models.CharField(max_length=50)),
                ("icon", models.CharField(max_length=6)),
                ("temperature", models.FloatField(max_length=6)),
                ("feels_like", models.FloatField(blank=True, max_length=6, null=True)),
                ("pressure", models.IntegerField(blank=True, null=True)),
                ("humidity", models.IntegerField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, max_length=6, null=True)),
                ("wind_direction", models.IntegerField(blank=True, null=True)),
                ("wind_gust", models.FloatField(blank=True, max_length=6, null=True)),
                ("clouds", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(max_length=2)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=50)),
                ("temp_unit", models.CharField(max_length=30)),
                ("speed_unit", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Current weather data",
                "verbose_name_plural": "Current weather data",
            },
        ),
        migrations.DeleteModel(
            name="CityWeather",
        ),
        migrations.CreateModel(
            name="HourlyWeather",
            fields=[
                (
                    "currentweather_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="weather.currentweather",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_time", models.DateTimeField()),
                (
                    "current_weather",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_data",
                        to="weather.currentweather",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hourly weather data",
                "verbose_name_plural": "Hourly weather data",
            },
            bases=("weather.currentweather",),
        ),
    ]
