# Generated by Django 5.0.1 on 2024-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_currentweather_delete_cityweather_hourlyweather"),
    ]

    operations = []
