# Generated by Django 5.0.1 on 2024-01-20 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0006_city_remove_hourlyweather_current_weather_weather_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hourlyweather",
            name="currentweather_ptr",
        ),
        migrations.RemoveField(
            model_name="hourlyweather",
            name="current_weather",
        ),
        migrations.DeleteModel(
            name="CurrentWeather",
        ),
        migrations.DeleteModel(
            name="HourlyWeather",
        ),
    ]
