# Generated by Django 5.0.1 on 2024-01-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0007_remove_hourlyweather_currentweather_ptr_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City data", "verbose_name_plural": "City data"},
        ),
        migrations.AlterField(
            model_name="weather",
            name="current",
            field=models.BooleanField(
                default=False,
                help_text="Field representing if record represents current weather or forecast data",
            ),
        ),
        migrations.AlterField(
            model_name="weather",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
