# Generated by Django 5.0.1 on 2024-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0008_alter_city_options_alter_weather_current_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="weather",
            constraint=models.UniqueConstraint(
                condition=models.Q(("current", True)),
                fields=("city",),
                name="unique_current_true",
            ),
        ),
    ]
